# This workflow will install Python dependencies, run tests with a variety of Python versions

name: Build

on:
  push:
    branches: [ master, dyn_sim ]
  pull_request:
    branches: [ master, dyn_sim ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -c "import platform; print(platform.platform()); print(platform.architecture())"
        python -m pip install --upgrade pip
        python -m pip install wheel
        pip install -r requirements_test.txt
        pip install git+https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park.git
        pip install git+https://github.com/QSD-Group/QSDsan.git
        pip install git+https://github.com/QSD-Group/EXPOsan.git
    - name: Test with numba
      run: |
        pytest . -v --disable-numba=0 --cov-report html --cov=biosteam --cov-report term-missing -m "not slow"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls }}
        COVERALLS_PARALLEL: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      run: |
        curl https://coveralls.io/webhook?repo_token=${{ secrets.coveralls }} -d "payload[build_num]=${{ github.sha }}&payload[status]=done"
